version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: mvertes/alpine-mongo
    networks:
     - back-tier
    ports:
     - "3001:3001"
networks:
  back-tier:
    driver: bridge
volumes:
  dependencies:
  db-data:
